/**
 * API para marcação de consultas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Compromisso } from './compromisso';


export interface Pessoa { 
    compromissos?: Array<Compromisso>;
    email?: string;
    idPessoa?: number;
    nomeCompleto?: string;
    senha?: string;
}
