/**
 * API para marcação de consultas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { MedicoBodyDto } from '../model/medicoBodyDto';
import { ObjectResponse } from '../model/objectResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MedicoControllerService {

    protected basePath = 'https://kbmg28-back.herokuapp.com/ws-consulta-medica';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * create
     * 
     * @param medico medico
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createUsingPOST1(medico: MedicoBodyDto, observe?: 'body', reportProgress?: boolean): Observable<ObjectResponse>;
    public createUsingPOST1(medico: MedicoBodyDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ObjectResponse>>;
    public createUsingPOST1(medico: MedicoBodyDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ObjectResponse>>;
    public createUsingPOST1(medico: MedicoBodyDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (medico === null || medico === undefined) {
            throw new Error('Required parameter medico was null or undefined when calling createUsingPOST1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ObjectResponse>(`${this.basePath}/medico/create`,
            medico,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteById
     * 
     * @param idPessoa idPessoa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteByIdUsingDELETE1(idPessoa: string, observe?: 'body', reportProgress?: boolean): Observable<ObjectResponse>;
    public deleteByIdUsingDELETE1(idPessoa: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ObjectResponse>>;
    public deleteByIdUsingDELETE1(idPessoa: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ObjectResponse>>;
    public deleteByIdUsingDELETE1(idPessoa: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPessoa === null || idPessoa === undefined) {
            throw new Error('Required parameter idPessoa was null or undefined when calling deleteByIdUsingDELETE1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idPessoa !== undefined && idPessoa !== null) {
            queryParameters = queryParameters.set('idPessoa', <any>idPessoa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<ObjectResponse>(`${this.basePath}/medico/deleteOne`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findAll
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findAllUsingGET1(observe?: 'body', reportProgress?: boolean): Observable<ObjectResponse>;
    public findAllUsingGET1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ObjectResponse>>;
    public findAllUsingGET1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ObjectResponse>>;
    public findAllUsingGET1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ObjectResponse>(`${this.basePath}/medico/all`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findOne
     * 
     * @param idPessoa idPessoa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findOneUsingGET1(idPessoa: string, observe?: 'body', reportProgress?: boolean): Observable<ObjectResponse>;
    public findOneUsingGET1(idPessoa: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ObjectResponse>>;
    public findOneUsingGET1(idPessoa: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ObjectResponse>>;
    public findOneUsingGET1(idPessoa: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPessoa === null || idPessoa === undefined) {
            throw new Error('Required parameter idPessoa was null or undefined when calling findOneUsingGET1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idPessoa !== undefined && idPessoa !== null) {
            queryParameters = queryParameters.set('idPessoa', <any>idPessoa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ObjectResponse>(`${this.basePath}/medico`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
